apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-deploy-webinar-pipelinerun
spec:
  pipelineRef:
    name: build-and-deploy
  params:
  - name: deployment-name
    value: webinar-site
  - name: git-url
    value: https://github.com/hupiper/webinar-site.git
  - name: IMAGE
    value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/webinar-site
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
